language: node_js
node_js:
- "0.10"

env:
  global:
    - secure: MCFaSupN6CbWrRjlZXmlxjXsUSNmAOhQHPnSpK0o8tlVwDLthlz527emN5BKIsPXgl+N+/U4kQK++NTbcgMqkSVPIC3u7S0xEBXAJS7JJdtsxOf1A4Pcgm8fCAXjHeyJvYL+xTGoxJtQ9k4BkxU9YtuIc3sX2Jy7HLVnTb+Ysl4=
    - secure: HKOgn0cwmvmOPRk0k5sjin+w04IAmRRNd1rcIBv7CX8qr10UdhhOSg6ckWCqFfL3senf6mfbahGC00a82vcxU0uhwyDP9vC+cGEXMspfZw6FNuZVcsn2Dgm1GyII/gBpCfcITUl08TkAVPCPgpvZVkOLtyTx3Bu4Cr5QCwXLMqs=

addons:
  sauce_connect: true


before_install:
  - npm install -g grunt-cli
  - npm install
  - bower install
